<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260420202600 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE task_run (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, input_text TEXT NOT NULL, output_text TEXT DEFAULT NULL, status VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, agent_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3FF45C473414710B ON task_run (agent_id)');
        $this->addSql('CREATE INDEX IDX_3FF45C47B03A8386 ON task_run (created_by_id)');
        $this->addSql('ALTER TABLE task_run ADD CONSTRAINT FK_3FF45C473414710B FOREIGN KEY (agent_id) REFERENCES agent (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_run ADD CONSTRAINT FK_3FF45C47B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE task_run DROP CONSTRAINT FK_3FF45C473414710B');
        $this->addSql('ALTER TABLE task_run DROP CONSTRAINT FK_3FF45C47B03A8386');
        $this->addSql('DROP TABLE task_run');
    }
}
